# Data Version Control pipeline configuration
# This file defines the stages for preparing canonical data

stages:
  prepare_patterns:
    cmd: python -m scripts.prepare_patterns
    deps:
      - scripts/prepare_patterns.py
    outs:
      - patterns/gyro_g1/v1/:
          cache: true
          persist: true
    params:
      - schema_version

  prepare_transitions:
    cmd: python -m scripts.prepare_transitions
    deps:
      - scripts/prepare_transitions.py
    outs:
      - transitions/gyro_g1/v1/:
          cache: true
          persist: true
    params:
      - schema_version

  validate_data:
    cmd: python -m scripts.validate_canonical_data
    deps:
      - scripts/validate_canonical_data.py
      - patterns/gyro_g1/v1/
      - transitions/gyro_g1/v1/
    metrics:
      - validation_report.json:
          cache: false

  test:
    cmd: pytest -xvs tests/
    deps:
      - gyro_si/
      - tests/
    metrics:
      - test_results.xml:
          cache: false

params:
  schema_version: 1
