# GyroSI Main Configuration

log:
  # Maximum log file size in bytes (default: 1MB)
  max_size: 1048576  # 1MB

  # Number of rotated log files to keep
  backup_count: 5

  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO

paths:
  # Directory for runtime logs
  log_dir: logs

  # Directory for persistent knowledge base
  knowledge_dir: knowledge
