name: Build Manifold Assets

on:
  workflow_dispatch:

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Build ontology_map.json
        run: |
          python -m baby.information ontology --output memories/public/ontology/ontology_map.json

      - name: Build phenomenology_map.json
        run: |
          python -m baby.information phenomenology --ontology_map memories/public/ontology/ontology_map.json --output memories/public/ontology/phenomenology_map.json

      - name: Build epistemology.npy
        run: |
          python -m baby.information epistemology --ontology memories/public/ontology/ontology_map.json --output memories/public/ontology/epistemology.npy

      - name: Add and commit LFS files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git lfs track "*.npy" "*.json"
          git add memories/public/ontology/ontology_map.json memories/public/ontology/phenomenology_map.json memories/public/ontology/epistemology.npy
          git commit -m "Add prebuilt ontology assets [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 